name: Passo 0 # Iniciar exercício

on:
  push:
    branches:
      - main

permissions:
  contents: write # Update Readme
  actions: write # Disable/enable workflows
  issues: write # Criar issue e comentar nas issues

env:
  STEP_1_FILE: ".github/steps/1-create-a-branch.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Iniciar exercício
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.8.1
    with:
      exercise-title: "Introdução ao GitHub"
      intro-message: "Se você é novo(a) no GitHub, talvez perceba que outras pessoas desenvolvedoras usam ___**issues**___ para organizar o trabalho e colaborar. Nós faremos o mesmo! Essa é uma outra lição, mas hoje vamos apresentar o básico."

  post_next_step_content:
    name: Publicar conteúdo do próximo passo
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}

    steps:
      - name: Baixar código
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Obter modelos de resposta
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Criar comentário - adicionar conteúdo do passo
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}

      - name: Criar comentário - acompanhando progresso
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Desabilitar workflow atual e habilitar o próximo
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
